language: cpp
compiler:
  - gcc
cache: apt
before_install:
  - yes | sudo apt-add-repository ppa:ubuntu-sdk-team/ppa
  - yes | sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 50
  - sudo apt-get install -qq zlib1g-dev qtdeclarative5-dev qtbase5-dev qtchooser
script: qtchooser -run-tool=qmake -qt=qt5 && sudo make install && make check
services:
  - postgresql