language: cpp
compiler:
  - gcc
cache: apt
before_install:
  - yes | sudo apt-add-repository ppa:ubuntu-sdk-team/ppa
  - yes | sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -qq
  - sudo apt-get install -qq zlib1g-dev qtdeclarative5-dev qtbase5-dev qtchooser
  - sudo apt-get install -qq g++-4.8
  - sudo rm /usr/bin/gcc /usr/bin/cpp /usr/bin/g++
  - sudo ln -s /usr/bin/gcc-4.8 /usr/bin/gcc
  - sudo ln -s /usr/bin/cpp-4.8 /usr/bin/cpp
  - sudo ln -s /usr/bin/g++-4.8 /usr/bin/g++
  - gcc -v
  - g++ -v
  - cpp -v
script: qtchooser -run-tool=qmake -qt=qt5 && sudo make install && make check
services:
  - postgresql