#ifndef NETWORKPROTOCOL_GLOBAL_H
#define NETWORKPROTOCOL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(NETWORKPROTOCOL_LIBRARY)
#  define NETWORKPROTOCOLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define NETWORKPROTOCOLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // NETWORKPROTOCOL_GLOBAL_H
